name: tpol-private
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.7.11
  - pip:
    - huggingface-hub==0.5.1
    - pandas==1.3.5
    - protobuf==3.20.0
    - regex==2022.3.15
    - tokenizers==0.12.1
    - torch==1.11.0
    - transformers==4.18.0
    - sentencepiece==0.1.97
